### ISSUE TITLE
PSCIS submission - photo validation

### ISSUE THREAD

**Issue by NewGraphEnvironment** [NewGraphEnvironment/fish_passage_fraser_2023_reporting#113]
related to https://github.com/NewGraphEnvironment/fish_passage_fraser_2023_reporting/issues/108 but made separate issue to help deal with all the detail

renaming of photos in this project done by hand. could consider scripting in the future if this actually addresses problem

its not just `barrel2` type photos its also `inletgrate` type of thing in the photo names.  

Seems like search ability within directories may differ between macs so done on Al's computer

![image](https://github.com/user-attachments/assets/a16ad80e-8339-4d2a-ba15-56b1fda5ef9d)
 

![image](https://github.com/user-attachments/assets/391bd1e3-8e23-4146-aba0-3682724f2ffe)

**Comment by NewGraphEnvironment** [comment]
had another submssion fail.  Cannot access proper error report currently due to password lockout. 

Worth noting that it does appear as though the number of issues on submission was much less this time indicating we are on the right track

found another culprit manually though

![image](https://github.com/user-attachments/assets/8cc141a3-e1f8-4e0b-9ba0-230215179f88)


Probably need to change the `fpr_photo_qa` function back to being more general so it will tell us where duplicates of the 5 reserved words are.  Lots of history here with assumption being that as long as on ly {reservedword.} was present we were good.  Seems to be not true but not 100% conrirmed

https://github.com/NewGraphEnvironment/fpr/issues?q=is%3Aissue+is%3Aopen+fpr_photo_qa+

https://github.com/NewGraphEnvironment/fpr/issues?q=is%3Aissue+is%3Aopen+fpr_photo_qa+

**Comment by NewGraphEnvironment** [comment]
20241028 submission.  Mostly same errors but this needs to be addressed. Working in original spreadsheet then moveing that to onedrive then to PC can be helpful.  

```
Crossing: 5400024. The supplied value of 12.0 is not valid for Structure Diameter or Span. If stream crossing type is Closed Bottom Structure then the value supplied must be > 0 and <=9.99 meters. If stream crossing type is Open Bottom Structure then the value supplied must be > 0 and <=300 meters. If the crossing type is Other than the value is not required.
```

will be worth it to try to find these reserved words again before submission. Understandign why existing tool from Brandwood isn't working could be helpful in case we can use it

**Comment by NewGraphEnvironment** [comment]
also

```
Crossing: 5400019. The supplied value of 99.9 is not valid for Structure Length. The value supplied must be >0 and <=99.0.
```

related to https://github.com/NewGraphEnvironment/fish_passage_fraser_2023_reporting/issues/108 and maybe should have put this there...

**Comment by lucy-schick** [comment]
Issue with the photo QA tool from Matt.

Looks like its an issue with the macros. Weird on the PC because it doesn't give me the option to enable or disable macros when opening the file (like it does on mac). I'm thinking maybe macros are just disable for the file, i'll start with that.

![{A0053B8B-7E1D-42E8-86CF-04A01DA62A4E}](https://github.com/user-attachments/assets/42429d41-a29f-4460-a8e4-f8e1ab836d7a)

**Comment by lucy-schick** [comment]
Data has been successfully submitted.

Although there were TONS of errors, some due to the metadata issues and some due to the duplicate reserve names, the reason we figured out duplicate reserve name photos were causing errors is because when we resubmitted the data after adding underscores, we got fewer errors.

**Comment by lucy-schick** [comment]
Closing in favour of https://github.com/NewGraphEnvironment/fish_passage_guidebook/issues/12 and
